export default [
  'ACT Department of Education and Training',
  'AIH Higher Education',
  'ANU College',
  'APM College of Business and Communication',
  'Ability Education',
  'Academia International',
  'Academies Australasia',
  'Academies Australasia Polytechnic Pty Limited',
  'Academy of Information Technology Pty Ltd',
  'Academy of Interactive Entertainment',
  'Access Language Centre',
  'Acknowledge Creativity',
  'All Saints Anglican School',
  'Alphacrucis College',
  'Anglican Schools Commission',
  'Annesley Junior School',
  'Apple Study Group',
  'Aranmore Catholic College',
  'Australasian College of Natural Therapies (ACNT)',
  'Australia-International Institute of Workplace Training',
  'Australian Catholic University',
  'Australian College of Agriculture and Horticulture',
  'Australian College of Applied Psychology',
  'Australian College of Physical Education',
  'Australian Language Schools Pty Ltd',
  'Australian Maritime College',
  'Australian National College of Beauty',
  'Australian Pacific College',
  'Australian Pacific Travel and Tourism',
  'Australian Wings Academy',
  'Avalon College',
  'Aviation Australia',
  'BCA National Training Group',
  'BROWNS English Language School',
  'Basair Aviation College',
  'Baxter Institute',
  'Billy Blue College of Design',
  'Blue Mountains International Hotel Management School',
  'Bond University',
  'Bond University College',
  'Box Hill Institute of TAFE',
  'Brisbane Grammar School',
  'CATC Design School',
  'CELUSA (Centre for English Language in the University of South Australia)',
  'CQUniversity Australia',
  'CQUniversity English Language Centre, Rockhampton and Gold Coast',
  'Cairns College of English and Business',
  'Camberwell Girls Grammar School',
  'Camberwell Grammar School',
  'Cambridge International College',
  'Canberra Institute of Technology',
  'Canning College',
  'Canterbury Business College',
  'Canterbury Language Academy',
  'Canterbury Technical Institute',
  'Carnegie Mellon University - Australia',
  'Centre for English Language Teaching, The University of Western Australia',
  'Centre for English Teaching - The University of Sydney',
  'Charles Darwin University',
  'Charles Sturt University',
  'Children\'s Service Education',
  'Chisholm Institute of TAFE',
  'Curtin College',
  'Curtin English Language Centre (CELC)',
  'Curtin University',
  'DNA Kingston Training',
  'Deakin College',
  'Deakin University',
  'Deakin University English Language Institute (DUELI)',
  'Department of Education and Child Development (Govt SA)',
  'Discover English',
  'ELS Universal English College',
  'ELTHAM College',
  'EQUALS International Pty Ltd',
  'Edith Cowan College',
  'Edith Cowan University',
  'Education Centre of Australia (ECA)',
  'Education Queensland International',
  'Educo Southern Cross University – Melbourne',
  'Educo Southern Cross University – Perth',
  'Educo Southern Cross University – Sydney',
  'Endeavour College of Natural Health',
  'English Language Company Australia Pty Ltd',
  'English Unlimited Brisbane',
  'Everthought College of Construction',
  'Excelsia College',
  'Eynesbury College',
  'Eynesbury College Academy of English',
  'Eynesbury Institute of Business and Technology',
  'Fahan School',
  'Federation University Australia',
  'Firbank Grammar School',
]
